In [75]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss, classification_report
import joblib

import warnings
warnings.filterwarnings('ignore')

In [12]:
df = pd.read_csv(r'../data/processed/model_features.csv', parse_dates=['date'])
df.head()

,neutral,home_rank,home_points,away_rank,away_points,rank_diff,tournament_bucket_continental_championship,tournament_bucket_friendly,tournament_bucket_other,tournament_bucket_world_cup,...,home_form_win_rate,home_form_goal_for,home_form_goal_against,away_form_win_rate,away_form_goal_for,away_form_goal_against,date,home_team,away_team,result_encoded
0,True,53.0,560.0,13.0,687.0,-40.0,1.0,0.0,0.0,0.0,...,1.00,3.00,1.0,0.6,1.6,1.0,2001-07-18,Peru,Mexico,2
1,True,69.0,516.0,33.0,610.0,-36.0,1.0,0.0,0.0,0.0,...,1.00,2.00,0.0,0.4,1.0,1.0,2001-07-19,Bolivia,Costa Rica,0
2,True,48.0,578.0,30.0,620.0,-18.0,1.0,0.0,0.0,0.0,...,0.67,1.33,2.0,0.6,1.8,1.0,2001-07-19,Honduras,Uruguay,2
3,False,109.0,404.0,29.0,621.0,-80.0,0.0,1.0,0.0,0.0,...,0.75,1.25,1.0,0.4,1.4,1.0,2001-07-19,Malaysia,Saudi Arabia,0
4,False,82.0,483.0,45.0,584.0,-37.0,0.0,1.0,0.0,0.0,...,0.60,1.00,2.0,0.4,1.8,1.0,2001-07-20,Cuba,Jamaica,1

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20929 entries, 0 to 20928
Data columns (total 21 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   neutral                                     20929 non-null  bool
 1   home_rank                                   20929 non-null  float64
 2   home_points                                 20929 non-null  float64
 3   away_rank                                   20929 non-null  float64
 4   away_points                                 20929 non-null  float64
 5   rank_diff                                   20929 non-null  float64
 6   tournament_bucket_continental_championship  20929 non-null  float64
 7   tournament_bucket_friendly                  20929 non-null  float64
 8   tournament_bucket_other                     20929 non-null  float64
 9   tournament_bucket_world_cup                 20929 non-null  float64
 10  tournament_bucket_world_cup_qualifier       20929 non-null  float64
 11  home_form_win_rate                          20929 non-null  float64
 12  home_form_goal_for                          20929 non-null  float64
 13  home_form_goal_against                      20929 non-null  float64
 14  away_form_win_rate                          20929 non-null  float64
 15  away_form_goal_for                          20929 non-null  float64
 16  away_form_goal_against                      20929 non-null  float64
 17  date                                        20929 non-null  datetime64[us]
 18  home_team                                   20929 non-null  str
 19  away_team                                   20929 non-null  str
 20  result_encoded                              20929 non-null  int64
dtypes: bool(1), datetime64[us](1), float64(16), int64(1), str(2)
memory usage: 3.2 MB

In [15]:
train = df[df['date'] <= '2025-01-1']
test = df[df['date'] > '2025-01-1']

In [18]:
train.tail()

,neutral,home_rank,home_points,away_rank,away_points,rank_diff,tournament_bucket_continental_championship,tournament_bucket_friendly,tournament_bucket_other,tournament_bucket_world_cup,...,home_form_win_rate,home_form_goal_for,home_form_goal_against,away_form_win_rate,away_form_goal_for,away_form_goal_against,date,home_team,away_team,result_encoded
19644,True,81.0,1302.86,155.0,1021.24,74.0,0.0,0.0,1.0,0.0,...,0.2,1.0,2.0,0.4,1.6,1.0,2024-12-28,Bahrain,Yemen,0
19645,False,116.0,1168.02,159.0,1008.26,43.0,0.0,0.0,1.0,0.0,...,0.2,1.2,2.0,0.4,1.6,1.0,2024-12-29,Vietnam,Singapore,2
19646,False,100.0,1218.56,147.0,1053.03,47.0,0.0,0.0,1.0,0.0,...,0.2,1.4,2.0,0.4,1.6,1.0,2024-12-30,Thailand,Philippines,2
19647,True,76.0,1326.18,56.0,1431.30,-20.0,0.0,0.0,1.0,0.0,...,0.4,1.8,2.0,0.4,1.6,2.0,2024-12-31,Oman,Saudi Arabia,2
19648,False,137.0,1098.42,81.0,1302.86,-56.0,0.0,0.0,1.0,0.0,...,0.6,2.0,2.0,0.4,1.6,2.0,2024-12-31,Kuwait,Bahrain,0

In [17]:
test.head()

,neutral,home_rank,home_points,away_rank,away_points,rank_diff,tournament_bucket_continental_championship,tournament_bucket_friendly,tournament_bucket_other,tournament_bucket_world_cup,...,home_form_win_rate,home_form_goal_for,home_form_goal_against,away_form_win_rate,away_form_goal_for,away_form_goal_against,date,home_team,away_team,result_encoded
19649,False,116.0,1168.02,100.0,1218.56,-16.0,0.0,0.0,1.0,0.0,...,0.6,1.8,1.0,0.4,1.2,2.0,2025-01-02,Vietnam,Thailand,2
19650,True,67.0,1375.16,108.0,1195.45,41.0,0.0,0.0,1.0,0.0,...,0.8,2.0,1.0,0.2,1.0,2.0,2025-01-04,Oman,Bahrain,0
19651,True,76.0,1326.18,81.0,1302.86,5.0,0.0,0.0,1.0,0.0,...,0.6,1.6,1.0,0.4,1.2,2.0,2025-01-04,Burkina Faso,Kenya,1
19652,False,100.0,1218.56,116.0,1168.02,16.0,0.0,0.0,1.0,0.0,...,0.4,1.2,1.0,0.4,1.2,1.0,2025-01-05,Thailand,Vietnam,0
19653,True,114.0,1174.99,108.0,1195.45,-6.0,0.0,0.0,1.0,0.0,...,0.2,1.2,2.0,0.6,1.6,1.0,2025-01-07,Tanzania,Kenya,0

In [64]:
feature_cols = ['neutral', 'home_rank', 'home_points', 'away_rank', 'away_points',
       'rank_diff', 'tournament_bucket_continental_championship',
       'tournament_bucket_friendly', 'tournament_bucket_other',
       'tournament_bucket_world_cup', 'tournament_bucket_world_cup_qualifier',
       'home_form_win_rate', 'home_form_goal_for', 'home_form_goal_against',
       'away_form_win_rate', 'away_form_goal_for', 'away_form_goal_against',]
target = ['result_encoded']

X_train = train[feature_cols]

y_train = train[target]

X_test = test[feature_cols]

y_test = test[target]

In [65]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(19649, 17)
(19649, 1)
(1280, 17)
(1280, 1)

In [66]:
# cheking if the model will predict draws or not
naive_preds = np.where(X_test["rank_diff"] > 0, 2, 0)  # 2=Home, 0=Away
naive_accuracy = accuracy_score(y_test, naive_preds)
print(f"Naive baseline accuracy: {naive_accuracy:.4f}")

Naive baseline accuracy: 0.4344

In [67]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression()

In [68]:
log_reg_pred = log_reg.predict(X_test)
log_reg_proba = log_reg.predict_proba(X_test)


print(f"Logistic Regression accuracy: {accuracy_score(y_test, log_reg_pred):.4f}")
print(f"Logistic Regression log-loss: {log_loss(y_test, log_reg_proba):.4f}")
print()
print(classification_report(y_test, log_reg_pred, target_names=["Away", "Draw", "Home"]))

Logistic Regression accuracy: 0.4844
Logistic Regression log-loss: 1.0435

              precision    recall  f1-score   support

        Away       0.37      0.02      0.04       378
        Draw       0.00      0.00      0.00       280
        Home       0.49      0.99      0.65       622

    accuracy                           0.48      1280
   macro avg       0.28      0.33      0.23      1280
weighted avg       0.35      0.48      0.33      1280

In [69]:
model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    objective="multi:softprob",
    num_class=3,
    eval_metric="mlogloss",
    random_state=42,
)

In [70]:
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None, num_class=3, ...)

In [71]:
xgb_pred = model.predict(X_test)
xgb_proba = model.predict_proba(X_test)
accuracy = accuracy_score(xgb_pred, y_test)

print(f"XGBoost accuracy: {accuracy_score(y_test, xgb_pred):.4f}")
print(f"XGBoost log-loss: {log_loss(y_test, xgb_proba):.4f}")
print()
print(classification_report(y_test, xgb_pred, target_names=["Away", "Draw", "Home"]))

XGBoost accuracy: 0.5070
XGBoost log-loss: 1.0380

              precision    recall  f1-score   support

        Away       0.48      0.21      0.29       378
        Draw       0.33      0.01      0.02       280
        Home       0.51      0.91      0.66       622

    accuracy                           0.51      1280
   macro avg       0.44      0.38      0.32      1280
weighted avg       0.46      0.51      0.41      1280

In [74]:
importance_df = pd.DataFrame({
    'features' : feature_cols,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

importance_df

                                      features  importance
0                                      neutral    0.208597
7                   tournament_bucket_friendly    0.097925
5                                    rank_diff    0.077452
10       tournament_bucket_world_cup_qualifier    0.052620
8                      tournament_bucket_other    0.051439
13                      home_form_goal_against    0.050371
2                                  home_points    0.044887
9                  tournament_bucket_world_cup    0.044713
1                                    home_rank    0.044580
4                                  away_points    0.044389
6   tournament_bucket_continental_championship    0.043224
11                          home_form_win_rate    0.041976
3                                    away_rank    0.041869
12                          home_form_goal_for    0.039457
15                          away_form_goal_for    0.039336
16                      away_form_goal_against    0.038609
14                          away_form_win_rate    0.038555

In [76]:
model_path = "../models/xgboost_v1.pkl"
joblib.dump(model, model_path)
print(f"Saved model to {model_path}")

Saved model to ../models/xgboost_v1.pkl

In [77]:
joblib.dump(feature_cols, "../models/feature_columns.pkl")

['../models/feature_columns.pkl']